name: 'Update .NET SDK'
description: 'Attempts to update the version of the .NET SDK used by the repository's global.json file.'
author: 'martincostello'
branding:
  icon: play
  color: blue
inputs:
  channel:
    description: 'The .NET release channel to download the SDK for (2.1, 3.1, 5.0, etc.).'
    required: true
  repo-token:
    description: 'The GitHub access token to use to create a Pull Request for any SDK update to the repository.'
    required: true
  branch-name:
    description: 'The optional Git branch name to use.'
    required: false
    default: ''
  commit-message:
    description: 'The optional Git commit message to use.'
    required: false
    default: ''
  global-json-file:
    description: 'The optional path to the global.json file to update.'
    required: false
    default: './global.json'
  user-email:
    description: 'The optional email address to use for the Git commit.'
    required: false
    default: 'github-actions[bot]@users.noreply.github.com'
  user-name:
    description: 'The optional user name to use for the Git commit.'
    required: false
    default: 'github-actions[bot]'
  dry-run:
    description: 'If true, the action will not actually make changes to the file system, Git or GitHub.'
    required: false
    default: true
outputs:
  pull-request-number:
    description: 'The number of the Pull Request created by the action if the .NET SDK is updated.'
  pull-request-html-url:
    description: 'The HTML URL of the Pull Request created by the action if the .NET SDK is updated.'
  sdk-updated:
    description: 'Whether the .NET SDK was updated by the action.'
  sdk-version:
    description: 'The latest version of the .NET SDK for the specified channel when the action completed.'
runs:
  using: 'node12'
  main: 'dist/index.js'
